apiVersion: v1
kind: Service
metadata:
  name: vllm-service # dns name other pods use to connect
spec:
  selector:
    app: vllm
  ports:
  - port: 8000
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  type: ClusterIP